ttsx/ds_user/urls.py
from django.conf.urls import url
import views

urlpatterns=[
    url(r'^register/$',views.register),
    url(r'^register_exist/$',views.register_exist),
    url(r'^register_handle/$',views.register_handle),
    url(r'^login/$',views.login),
    url(r'^login_handle/$',views.login_handle),
    url(r'^logout/$',views.logout),
    url(r'^user_center_info/$',views.user_center_info),
    url(r'^user_center_order(\d*)/$',views.user_center_order),
    url(r'^user_center_site/$',views.user_center_site)

]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('ds_user.urls')),
    url(r'^',include('ds_goods.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^cart/',include('ds_cart.urls')),
    url(r'^order/',include('ds_order.urls'))

]

ttsx/ds_order/models.py
#coding=utf-8
from django.db import models
# Create your models here.

class OrderInfo(models.Model):
    '''订单'''
    oid = models.CharField(max_length=20,primary_key=True)#编号：时间＋用户编号
    user = models.ForeignKey('ds_user.User')# 用户
    odate = models.DateTimeField(auto_now_add=True)# 日期
    oIsPay = models.BooleanField(default=False)# 是否支付
    ototal = models.DecimalField(max_digits=10,decimal_places=2)# 订单金额
    oaddress = models.CharField(max_length=255)# 收货地址


class OrderDetailInfo(models.Model):
    '''订单详细列表'''
    goods = models.ForeignKey('ds_goods.GoodsInfo')# 商品
    order = models.ForeignKey(OrderInfo)# 订单
    pirce = models.DecimalField(max_digits=5,decimal_places=2)# 价格
    count = models.IntegerField()# 数量

ttsx/ds_user/models.py
# coding=utf-8
from django.db import models

# Create your models here.

class User(models.Model):
    uname = models.CharField(max_length=20) # 用户名
    upasswd = models.CharField(max_length=40) # 用户密码
    ue_mail = models.CharField(max_length=30)# 用户邮箱
    utel = models.CharField(max_length=11)# 用户电话
    rec_name = models.CharField(max_length=20, default='')  # 收件人姓名
    rec_tel = models.CharField(max_length=11,default='') # 收件人电话
    rec_add = models.CharField(max_length=255,default='') # 收件人地址
    rec_postcode = models.CharField(max_length=6,default='') # 收件人邮编
    class Meta:
        db_table = "user"

ttsx/ds_user/views.py
# coding=utf-8
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpRequest,JsonResponse,HttpResponseRedirect
from models import *
from hashlib import sha1
from . import user_decorator
from django.core.paginator import Paginator,Page
from ds_goods.models import *
from ds_order.models import *
# Create your views here.


def register(request):
    return render(request,'ds_user/register.html')# 显示注册页

def register_handle(request):
    # 注册提交处理页面
    post = request.POST # 创建一个post对象
    uname = post.get('user_name')# 获取提交的名字属性
    upwd = post.get('pwd') #　获取提交的密码
    ucpwd = post.get('cpwd')# 获取提交的二次密码
    uemail = post.get('email')# 获取注册的邮箱

    s1 = sha1()# 创建一个sha1对象
    s1.update(upwd)# 将密码加密
    upwd2 = s1.hexdigest()# 获取加密后的密码
    user = User()# 创建一个ｕser对象
    user.uname = uname# 添加name属性
    user.upasswd = upwd2# 添加密码属性
    user.ue_mail = uemail# 添加邮箱属性
    user.save()# 将数据保存添加
    return redirect('/login/')# 注册成功跳转到登陆页

def register_exist(request):# 进行注册验证
    uname = request.GET.get('uname')# 获取用户输入的name
    count = User.objects.filter(uname=uname).count()# 在数据库查找获取到的名字个数,如果为１就证明已经存在
    return JsonResponse({'count':count})# 返回一个ｊｓｏｎ对象


def login(request):
    uname = request.COOKIES.get('uname','')# 获取cookie里的uname信息,让它默认在输入框中
    context = {'uname':uname,'error_name':0,'error_pwd':0}
    return render(request,'ds_user/login.html',context)

def login_handle(request):
    post = request.POST# 获取一个post对象
    uname = post.get('username')# 以post的方式获取名字
    upwd = post.get('pwd')# 以post的方式获取密码
    jizhu = post.get('jizhu',0)# 获取记住的值，如果选中会返回一个１，如果没有选中默认为０

    users = User.objects.filter(uname=uname)#　根据名字去数据库查找

    if len(users) == 1:# 如果查到
        s1 = sha1()# 创建一个sha１对象
        s1.update(upwd)# 将密码添加给s1
        if s1.hexdigest() == users[0].upasswd:# 将现在加密的密码和之前加密的密码进行对比
            url = request.COOKIES.get('ulr','/')
            red = HttpResponseRedirect(url)
            red.set_cookie('url','',max_age=-1)
            if jizhu != 0:
                red.set_cookie('uname',uname)
            else:
                red.set_cookie('uname','',max_age=-1)
            request.session['user_id']=users[0].id
            request.session['user_name']=uname
            request.session.set_expiry(0)
            return red
        else:
            context = {'uname': uname, 'error_name': 0, 'error_pwd': 1}
            return render(request,'ds_user/login.html',context)
    else:
        context = {'uname': uname, 'error_name': 1, 'error_pwd': 0}
        return render(request, 'ds_user/login.html', context)


def logout(request):
    request.session.flush()
    return redirect('/')

@user_decorator.login
def user_center_info(request):
    user = User.objects.get(id=request.session.get('user_id',''))
    goods_list = []
    goods_ids = request.COOKIES.get('liulan','')
    request.session['liulan'] = goods_ids
    request.session.set_expiry(60)

    #最近浏览
    if goods_ids != '':
        goods_ids1 = goods_ids.split(',')

        for goods_ids in goods_ids1:
            goods_list.append(GoodsInfo.objects.get(id = int(goods_ids)))

    tel = user.utel
    if tel == '':
        tel = "无"
        context = {'uname':user.uname,'utel':tel,'uemail':user.ue_mail,'goods_list':goods_list}
    return render(request,'ds_user/user_center_info.html',context)

@user_decorator.login
def user_center_order(request,pindex):
    order_list = OrderInfo.objects.filter(user_id=request.session['user_id']).order_by('-oid')
    paginator = Paginator(order_list, 10)
    if pindex == '':
        pindex = 1
    page = paginator.page(int(pindex))
    context = {'paginator':paginator,'page':page,'order_list':order_list}
    return render(request,'ds_user/user_center_order.html',context)

@user_decorator.login
def user_center_site(request):
    user = User.objects.get(id=request.session.get('user_id',''))
    if request.method == 'POST':
        post = request.POST
        user.rec_name = post.get('rec_name')
        user.rec_tel = post.get('rec_tel')
        user.rec_add = post.get('rec_add')
        user.rec_postcode = post.get('rec_postcode')
        user.save()
    return render(request,'ds_user/user_center_site.html',{'user':user})

ttsx/templates/ds_user/login.html
{%extends 'base.html'%}
{%block title%}<title>天天生鲜-登录</title>{%endblock title%}
{%block head%}
	<script type="text/javascript">
	$(function(){
		name_error=false;
	    pwd_error=false;

	    if({{error_name}}==1){
	    	$('.user_error').html('用户名或者密码错误').show();
	    }

	    if({{error_pwd}}==1){
	    	$('.pwd_error').html('用户名或者密码错误').show();
	    }

		$('.name_input').blur(function(){
			if($('.name_input').val()==0){
				$('.user_error').html('请输入用户名').show();
				name_error=false;
			}
			else{
				$('.user_error').hide();
				name_error=true;
			}

		});


		$('.pass_input').blur(function(){
			if($('.pass_input').val()==0){
				$('.pwd_error').html('请输入密码').show();
				pwd_error=false;
				}
			else{
				$('.pwd_error').hide();
				pwd_error=true;
			}

		});


		$('form').submit(function(){
			$('.name_input').blur();
			$('.pass_input').blur();
			return name_error && pwd_error;
		});

		})


	</script>

{%endblock head%}
{%block body1%}
<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
</div>
{%endblock body1%}
{%block body%}


	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="/login_handle/">
						{%csrf_token%}
						<input type="text" name="username" class="name_input" value="{{uname}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{%endblock body%}

ttsx/templates/ds_user/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-注册</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/register_handle/" id="reg_form">
					{%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

ttsx/templates/ds_user/user_center_info.html
{%extends 'base_foot.html'%}

{%block content%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user_center_info/" class="active">· 个人信息</a></li>
				<li><a href="/user_center_order/">· 全部订单</a></li>
				<li><a href="/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{uname}}</li>
							<li><span>联系方式：</span>{{utel}}</li>
							<li><span>邮箱地址：</span>{{uemail}}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
						{% for goods in goods_list%}
				<li>
					<a href="/detail{{goods.id}}/"><img src="/static/{{goods.gpic}}"></a>
					<h4><a href="/detail{{goods.id}}/">{{goods.gtitle}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{goods.gprice}}</span>
						<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
						<a href="/cart/add{{goods.id}}_1/" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
						{%endfor%}

			</ul>
		</div>
		</div>
	</div>


{%endblock content%}

ttsx/templates/ds_user/user_center_order.html
{%extends 'base_foot.html'%}

{%block head%}
<script>
$(function(){
	$('.col04').each(function(){
		count = parseInt($(this).prev().text());
		price = parseFloat($(this).prev().prev().find('span').text());
		$(this).text((count*price).toFixed(2)+'元')


});



});

</script>
{%endblock head%}


{%block content%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user_center_info/">· 个人信息</a></li>
				<li><a href="/user_center_order/" class="active">· 全部订单</a></li>
				<li><a href="/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>

		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
			{%if paginator.count > 0%}
				{% for order in page%}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.odate}}</li>
					<li class="col02">订单号：{{order.oid}}</li>
					<li class="col02 stress">{%if order.oIsPay%}已支付{%else%}未支付{%endif%}</li>
				</ul>


				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">


					{%for detail in order.orderdetailinfo_set.all%}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{detail.goods.gpic}}"></li>
									<li class="col02">{{detail.goods.gtitle|slice:'10'}}<em><span>{{detail.goods.gprice}}</span></span>元/{{detail.goods.gunit}}</em></li>
									<li class="col03">{{detail.count}}</li>
									<li class="col04">0</li>
								</ul>
					{%endfor%}

							</td>
							{%if order.oIsPay%}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
							{%else%}
							<td width="15%">{{order.ototal}}元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="/order/pay{{order.oid}}" class="oper_btn">去付款</a></td>
							{%endif%}
						</tr>
					</tbody>
				</table>
				{%endfor%}
			<div class="pagenation">
				{%if page.has_previous%}
				<a href="/user_center_order{{page.previous_page_number}}/"><上一页</a>
				{%endif%}

				{%for index in page.paginator.page_range%}
					{%if index == page.number%}
						<a href="#" class="active">{{index}}</a>
					{%else%}
						<a href="/user_center_order/">{{index}}</a>
					{%endif%}
				{%endfor%}

				{%if page.has_next%}
					<a href="/user_center_order{{page.next_page_number}}/">下一页></a>
				{%endif%}
			</div>
			{%else%}
			暂无订单信息


	</div>
	</div>

{%endif%}
{%endblock content%}

ttsx/templates/ds_user/user_center_site.html
{%extends 'base_foot.html'%}

{%block content%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user_center_info/">· 个人信息</a></li>
				<li><a href="/user_center_order/">· 全部订单</a></li>
				<li><a href="/user_center_site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{user.rec_add}} {{user.rec_name}} {{user.rec_tel}}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user_center_site/" method="post">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="rec_name" value="{{user.rec_name}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="rec_add">{{user.rec_add}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="rec_postcode" value="{{user.rec_postcode}}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="rec_tel" value="{{user.rec_tel}}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>


{%endblock content%}